force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <description>An object to store the car information.</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>This is a picklist for defining the car category.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>MUV</fullName>
            </value>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This field is for describing a car.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <description>Field</description>
    <inlineHelpText>Field to specify car&apos;s maker.</inlineHelpText>
    <label>Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CarController.cls
public with sharing class CarController {
    
    // wrapper class
    public class Filters {
        @AuraEnabled public String searchKey {get;set;}        
        @AuraEnabled public Decimal maxPrice {get;set;}
        @AuraEnabled public String[] categories {get;set;}
        @AuraEnabled public String[] makers {get;set;}
    }

    @AuraEnabled (Cacheable = true)
    public static List<Car__c> getCars(Filters filters) {
        String key, whereClause = '';
        Decimal maxPrice;

        List<String> criteria = new List<String>{};
        String [] categories;
        String [] makers;
        
        if (filters != null) {
            maxPrice = filters.maxPrice;
            categories = filters.categories;
            makers = filters.makers;

            if (!String.isEmpty(filters.searchKey)) {
                key = '%' + filters.searchKey + '%';
                criteria.add('Name LIKE : key');
            }

            if (filters.maxPrice >= 0) {
                criteria.add('MSRP__c <= : maxPrice');
            }  

            if (filters.categories != null) {
                criteria.add('Category__c IN : categories');
            }

            if (filters.makers != null) {
                criteria.add('Make__c IN : makers');
            }

            if (criteria.size() > 0 ) {
                whereClause = 'WHERE ' + String.join(criteria, ' AND ');
            }
        }

        String query = 'SELECT Id, Name, MSRP__c, Description__c, Category__c, Picture_URL__c ' 
        + 'FROM Car__c ' +
        whereClause + ' WITH SECURITY_ENFORCED' + ' ORDER BY Name';

        System.debug(query);

        return Database.query(query);
    }
}